---
  # - name: check for wp-cli
  #   file: src=/usr/local/bin/wp dest=/usr/bin/wp state=link
  #   ### never use dashes in variable names, they will break everything
  #   register: result
  #   ignore_errors: true


  - name: install wp-cli
    # sudo: false
    # when: result|changed
    command: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    ignore_errors: true

  - name: make wp-cli shortcut
    # when: result|changed
    command: chmod +x wp-cli.phar
    ignore_errors: true

  - name: make /var/www/default/htdocs
    # when: result|changed
    command: sudo mv wp-cli.phar /usr/local/bin/wp
    ignore_errors: true

  - name: download wordpress
    # when: result|changed
    sudo: false
    command: wp core download --path={{ site_path }}
    ignore_errors: true

  - name: create wp-config
    # when: result|changed
    sudo: false
    command: wp core config --dbname={{ database_name }} --dbuser={{ database_username }} --dbpass={{ database_password }} --path={{ site_path }} 
    ignore_errors: true

  - name: create wp database
    # when: result|changed
    sudo: false
    command: wp db create --path={{ site_path }}
    ignore_errors: true

  - name: install wordpress
    # when: result|changed
    sudo: false
    command: wp core install --path={{ site_path }} --url={{ ip_address }} --title={{ wp_site_title }} --admin_user={{ wp_admin_username }} --admin_password={{ wp_admin_password }} --admin_email={{ wp_admin_email }}
    ignore_errors: true

  - name: set up permalinks
    # when: result|changed
    sudo: false
    command: wp rewrite structure '/blog/%postname%' --path={{ site_path }}
    ignore_errors: true
    notify:
    - restart apache2
    - restart php5-fpm